[project]
name = "TN"
version = "0.1.0"
description = "Заметки в виде телеграм-чата"
requires-python = ">=3.10"
license = { text = "GPL-3.0-or-later" }
authors = [{ name = "DezFix" }]
dependencies = [
    "flet>=0.82.0",
    "Pillow>=10.0.0",
]

[tool.flet]
org = "app.tn"
project = "TN"
product = "TN"
build_number = 1